
DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S.%fZ'

MONDAY_INT = 1
TUESDAY_INT = 2
WEDNESDAY_INT = 3
THURSDAY_INT = 4
FRIDAY_INT = 5
SATURDAY_INT = 6
SUNDAY_INT = 7

MONDAY_STR = 'Monday'
TUESDAY_STR = 'Tuesday'
WEDNESDAY_STR = 'Wednesday'
THURSDAY_STR = 'Thursday'
FRIDAY_STR = 'Friday'
SATURDAY_STR = 'Saturday'
SUNDAY_STR = 'Sunday'
