Capstone - Backend: routing.serializers.route.RouteSerializer Class Reference
routing.serializers.route.RouteSerializer Class Reference
Static Public Attributes
id = serializers.IntegerField()
total_quantity = serializers.IntegerField()
total_distance = serializers.IntegerField()
total_duration = serializers.FloatField()
created_on = serializers.DateTimeField()
assigned_to = serializers.CharField()
Member Data Documentation
assigned_to
routing.serializers.route.RouteSerializer.assigned_to = serializers.CharField() static
created_on
routing.serializers.route.RouteSerializer.created_on = serializers.DateTimeField() static
Referenced by routing.models.route.Route.get_created_on().
id
routing.serializers.route.RouteSerializer.id = serializers.IntegerField() static
total_distance
routing.serializers.route.RouteSerializer.total_distance = serializers.IntegerField() static
Referenced by routing.models.route.Route.get_total_distance(), routing.models.route.Route.undo(), and routing.models.route.Route.update_properties().
total_duration
routing.serializers.route.RouteSerializer.total_duration = serializers.FloatField() static
Referenced by routing.models.route.Route.get_total_duration(), routing.models.route.Route.undo(), and routing.models.route.Route.update_properties().
total_quantity
routing.serializers.route.RouteSerializer.total_quantity = serializers.IntegerField() static
Referenced by routing.models.route.Route.get_total_demand(), routing.models.route.Route.undo(), and routing.models.route.Route.update_properties().
The documentation for this class was generated from the following file:
serializers/route.py