Capstone - Backend: routing.tests.main Namespace Reference
routing.tests.main Namespace Reference
Functions
def add_driver (db_connection)
def add_locations (db_connection)
def add_availability (db_connection)
Variables
DATABASE_URL
url
def all_drivers = add_driver(db_connection=db)
def all_locations = add_locations(db_connection=db)
def all_days = add_availability(db_connection=db)
Function Documentation
add_availability()
def routing.tests.main.add_availability (db_connection)
References routing.tests.main.add_availability().
Referenced by routing.tests.main.add_availability().
add_driver()
def routing.tests.main.add_driver (db_connection)
References routing.tests.main.add_driver().
Referenced by routing.tests.main.add_driver().
add_locations()
def routing.tests.main.add_locations (db_connection)
References routing.tests.main.add_locations().
Referenced by routing.tests.main.add_locations().
Variable Documentation
all_days
def routing.tests.main.all_days = add_availability(db_connection=db)
all_drivers
def routing.tests.main.all_drivers = add_driver(db_connection=db)
all_locations
def routing.tests.main.all_locations = add_locations(db_connection=db)
DATABASE_URL
routing.tests.main.DATABASE_URL
url
routing.tests.main.url